services:
  secdb:
    image: postgres:15.3-alpine
    container_name: secdb
    restart: unless-stopped
    labels:
      - traefik.enable=false
    networks:
      - finexonet
    env_file:
      - dbp.env
    ports:
      - "5457:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - finexopgdata:/var/lib/postgresql/data
      - finexopgconf:/etc/postgresql
      - finexopglog:/var/log/postgresql
  finexo:
    depends_on: [ secdb ]
    container_name: finexo
    image: finexo
    restart: unless-stopped
    environment:
      - ROD_CACHE_DIR=/go/bin/.cache/rod
    volumes:
      - rod-cache:/go/bin/.cache/rod
    cap_add:
      - SYS_ADMIN
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5869/healthcheck"]
    labels:
      - traefik.http.routers.finexo.rule=Host(`finexo.dmz.urx.ink`)
      - traefik.http.routers.finexo.entrypoints=web,websecure
      - traefik.http.routers.finexo.service=finexo
      - traefik.http.services.finexo.loadbalancer.server.port=5869
      - traefik.http.routers.finexo.tls=true
      - traefik.http.routers.finexo.tls.certresolver=le
      - traefik.http.middlewares.forwardedheaders.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.forwardedheaders.headers.customrequestheaders.X-Forwarded-For={ip}
      - traefik.http.routers.finexo.middlewares=forwardedheaders
      - traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Upgrade=websocket
      - traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Connection=Upgrade
      - traefik.http.routers.finexo.middlewares=websocket-headers
      - traefik.port=80
    networks:
      - finexonet
      - proxy
      - monitor
    ports:
      - 5869:5869

networks:
  proxy:
    external: true
  finexonet:
    driver: bridge
    external: false
  monitor:
    external: true

volumes:
  finexopgdata:
    driver: local
  finexopgconf:
    driver: local
  finexopglog:
    driver: local
  rod-cache:
