package tools

const MB_DATA_KEYS = ".price-data-area dt"
const MB_DATA_VALUES = ".price-data-area strong"

const YH_EXCHANGE_SELECTOR = "span.exchange span"
const YH_DISCOVER_SEEDS_SELECTOR = ".carousel-top a.card-link"
const YH_CURRENCY_SELECTOR = "span.exchange span:nth-child(3)"
const YH_FULLNAME_SELECTOR = "section.container.paddingRight"
const YH_REIT_HINT_SELECTOR = "h2.yf-1d08kze"
const YH_ETF_HINT_SELECTOR = "h3.yf-1ja4ll8"
const YH_PRICE_SELECTOR = "span[data-testid='qsp-price']"
const YH_PCHANGE_SELECTOR = "span[data-testid='qsp-price-change']"
const YH_PRICE_PERCENTAGE_CHANGE_SELECTOR = "span[data-testid='qsp-price-change-percent']"
const YH_YEARLY_RANGE_SELECTOR = "[data-field='fiftyTwoWeekRange']"
const YH_DAILY_RANGE_SELECTOR = "[data-field='regularMarketDayRange']"
const YH_MARKET_CAP_SELECTOR = "[data-field='marketCap']"
const YH_VOLUME_SELECTOR = "[data-field='regularMarketVolume']"
const YH_AVG_VOLUME_SELECTOR = "[data-field='averageVolume']"
const YH_BETA_SELECTOR = "span[title='Beta (5Y Monthly)'] ~ span"
const YH_PCLOSE_SELECTOR = "[data-field='regularMarketPreviousClose']"
const YH_COPEN_SELECTOR = "[data-field='regularMarketOpen']"
const YH_TARGET_SELECTOR = "[data-field='targetMeanPrice']"
const YH_BID_SELECTOR = "span[title='Bid'] ~ span"
const YH_ASK_SELECTOR = "span[title='Ask'] ~ span"
const YH_STOCK_DATA_SELECTOR = "[data-field='trailingPE']"
const YH_AUM_SELECTOR = "span[title='Net Assets'] ~ span"
const YH_ER_SELECTOR = "span[title='Expense Ratio (net)'] ~ span"
const YH_NAV_SELECTOR = "span[title='NAV'] ~ span"
const YH_ETF_DATA_SELECTOR = "section[data-testid='company-overview-card'] p[title]"
const YH_HOLDINGS_TICKERS_SELECTOR = "section[data-testid='top-holdings'] a[data-testid='ticker-container']"
const YH_HOLDING_ALLOCATIONS_SELECTOR = "section[data-testid='top-holdings'] a[data-testid='ticker-container'] ~ span.data"
const YH_YIELD_SELECTOR = "span[title='Yield'] ~ span"
const YH_FWD_YIELD_SELECTOR = "span[title='Forward Dividend & Yield'] ~ span"
